# Generated by Django 5.0.2 on 2024-03-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
